package models

import (
	"fmt"

	"gorm.io/gorm"
)

type Country struct {
	gorm.Model
	CountryName string
	Towns       []Town
}

var CountryList = []Country{
	{CountryName: "Afghanistan"},
	{CountryName: "Albania"},
	{CountryName: "Algeria"},
	{CountryName: "Andorra"},
	{CountryName: "Angola"},
	{CountryName: "Antigua and Barbuda"},
	{CountryName: "Argentina"},
	{CountryName: "Armenia"},
	{CountryName: "Australia"},
	{CountryName: "Austria"},
	{CountryName: "Azerbaijan"},
	{CountryName: "Bahamas"},
	{CountryName: "Bahrain"},
	{CountryName: "Bangladesh"},
	{CountryName: "Barbados"},
	{CountryName: "Belarus"},
	{CountryName: "Belgium"},
	{CountryName: "Belize"},
	{CountryName: "Benin"},
	{CountryName: "Bhutan"},
	{CountryName: "Bolivia"},
	{CountryName: "Bosnia and Herzegovina"},
	{CountryName: "Botswana"},
	{CountryName: "Brazil"},
	{CountryName: "Brunei"},
	{CountryName: "Bulgaria"},
	{CountryName: "Burkina Faso"},
	{CountryName: "Burundi"},
	{CountryName: "Cabo Verde"},
	{CountryName: "Cambodia"},
	{CountryName: "Cameroon"},
	{CountryName: "Canada"},
	{CountryName: "Central African Republic"},
	{CountryName: "Chad"},
	{CountryName: "Chile"},
	{CountryName: "China"},
	{CountryName: "Colombia"},
	{CountryName: "Comoros"},
	{CountryName: "Congo, Democratic Republic of the"},
	{CountryName: "Congo, Republic of the"},
	{CountryName: "Costa Rica"},
	{CountryName: "Croatia"},
	{CountryName: "Cuba"},
	{CountryName: "Cyprus"},
	{CountryName: "Czech Republic"},
	{CountryName: "Denmark"},
	{CountryName: "Djibouti"},
	{CountryName: "Dominica"},
	{CountryName: "Dominican Republic"},
	{CountryName: "Ecuador"},
	{CountryName: "Egypt"},
	{CountryName: "El Salvador"},
	{CountryName: "Equatorial Guinea"},
	{CountryName: "Eritrea"},
	{CountryName: "Estonia"},
	{CountryName: "Eswatini"},
	{CountryName: "Ethiopia"},
	{CountryName: "Fiji"},
	{CountryName: "Finland"},
	{CountryName: "France"},
	{CountryName: "Gabon"},
	{CountryName: "Gambia"},
	{CountryName: "Georgia"},
	{CountryName: "Germany"},
	{CountryName: "Ghana"},
	{CountryName: "Greece"},
	{CountryName: "Grenada"},
	{CountryName: "Guatemala"},
	{CountryName: "Guinea"},
	{CountryName: "Guinea-Bissau"},
	{CountryName: "Guyana"},
	{CountryName: "Haiti"},
	{CountryName: "Honduras"},
	{CountryName: "Hungary"},
	{CountryName: "Iceland"},
	{CountryName: "India"},
	{CountryName: "Indonesia"},
	{CountryName: "Iran"},
	{CountryName: "Iraq"},
	{CountryName: "Ireland"},
	{CountryName: "Israel"},
	{CountryName: "Italy"},
	{CountryName: "Jamaica"},
	{CountryName: "Japan"},
	{CountryName: "Jordan"},
	{CountryName: "Kazakhstan"},
	{CountryName: "Kenya"},
	{CountryName: "Kiribati"},
	{CountryName: "Korea, North"},
	{CountryName: "Korea, South"},
	{CountryName: "Kosovo"},
	{CountryName: "Kuwait"},
	{CountryName: "Kyrgyzstan"},
	{CountryName: "Laos"},
	{CountryName: "Latvia"},
	{CountryName: "Lebanon"},
	{CountryName: "Lesotho"},
	{CountryName: "Liberia"},
	{CountryName: "Libya"},
	{CountryName: "Liechtenstein"},
	{CountryName: "Lithuania"},
	{CountryName: "Luxembourg"},
	{CountryName: "Madagascar"},
	{CountryName: "Malawi"},
	{CountryName: "Malaysia"},
	{CountryName: "Maldives"},
	{CountryName: "Mali"},
	{CountryName: "Malta"},
	{CountryName: "Marshall Islands"},
	{CountryName: "Mauritania"},
	{CountryName: "Mauritius"},
	{CountryName: "Mexico"},
	{CountryName: "Micronesia"},
	{CountryName: "Moldova"},
	{CountryName: "Monaco"},
	{CountryName: "Mongolia"},
	{CountryName: "Montenegro"},
	{CountryName: "Morocco"},
	{CountryName: "Mozambique"},
	{CountryName: "Myanmar"},
	{CountryName: "Namibia"},
	{CountryName: "Nauru"},
	{CountryName: "Nepal"},
	{CountryName: "Netherlands"},
	{CountryName: "New Zealand"},
	{CountryName: "Nicaragua"},
	{CountryName: "Niger"},
	{CountryName: "Nigeria"},
	{CountryName: "North Macedonia"},
	{CountryName: "Norway"},
	{CountryName: "Oman"},
	{CountryName: "Pakistan"},
	{CountryName: "Palau"},
	{CountryName: "Palestine"},
	{CountryName: "Panama"},
	{CountryName: "Papua New Guinea"},
	{CountryName: "Paraguay"},
	{CountryName: "Peru"},
	{CountryName: "Philippines"},
	{CountryName: "Poland"},
	{CountryName: "Portugal"},
	{CountryName: "Qatar"},
	{CountryName: "Romania"},
	{CountryName: "Russia"},
	{CountryName: "Rwanda"},
	{CountryName: "Saint Kitts and Nevis"},
	{CountryName: "Saint Lucia"},
	{CountryName: "Saint Vincent and the Grenadines"},
	{CountryName: "Samoa"},
	{CountryName: "San Marino"},
	{CountryName: "Sao Tome and Principe"},
	{CountryName: "Saudi Arabia"},
	{CountryName: "Senegal"},
	{CountryName: "Serbia"},
	{CountryName: "Seychelles"},
	{CountryName: "Sierra Leone"},
	{CountryName: "Singapore"},
	{CountryName: "Slovakia"},
	{CountryName: "Slovenia"},
	{CountryName: "Solomon Islands"},
	{CountryName: "Somalia"},
	{CountryName: "South Africa"},
	{CountryName: "South Sudan"},
	{CountryName: "Spain"},
	{CountryName: "Sri Lanka"},
	{CountryName: "Sudan"},
	{CountryName: "Suriname"},
	{CountryName: "Sweden"},
	{CountryName: "Switzerland"},
	{CountryName: "Syria"},
	{CountryName: "Taiwan"},
	{CountryName: "Tajikistan"},
	{CountryName: "Tanzania"},
	{CountryName: "Thailand"},
	{CountryName: "Timor-Leste"},
	{CountryName: "Togo"},
	{CountryName: "Tonga"},
	{CountryName: "Trinidad and Tobago"},
	{CountryName: "Tunisia"},
	{CountryName: "Turkey"},
	{CountryName: "Turkmenistan"},
	{CountryName: "Tuvalu"},
	{CountryName: "Uganda"},
	{CountryName: "Ukraine"},
	{CountryName: "United Arab Emirates"},
	{CountryName: "United Kingdom"},
	{CountryName: "United States"},
	{CountryName: "Uruguay"},
	{CountryName: "Uzbekistan"},
	{CountryName: "Vanuatu"},
	{CountryName: "Vatican City"},
	{CountryName: "Venezuela"},
	{CountryName: "Vietnam"},
	{CountryName: "Yemen"},
	{CountryName: "Zambia"},
	{CountryName: "Zimbabwe"},
}

func (c *Country) save() error {
	if err := DB.Create(&c).Error; err != nil {
		return fmt.Errorf("failed to create country: %w", err)
	}
	return nil
}

func AddCountries() error {
	for _, country := range CountryList {
		if err := country.save(); err != nil {
			return fmt.Errorf("failed to add countries: %w", err)
		}
	}
	return nil
}

func GetAllCountries() ([]Country, error) {
	var countries []Country

	if err := DB.Order("country_name").Find(&countries).Error; err != nil {
		return nil, fmt.Errorf("failed to retrieve countries: %w", err)
	}
	return countries, nil
}
